model:
  yolo_model: 'yolov8n.pt'  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  confidence: 0.5
  iou_threshold: 0.45
  
traffic_signs:
  classes:
    - 'stop'
    - 'yield'
    - 'speed_limit'
    - 'no_entry'
    - 'one_way'
    - 'parking'
    - 'pedestrian_crossing'
    - 'school_zone'
    - 'construction'
  
pose:
  model_complexity: 1  # 0, 1, or 2
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  
video:
  input_resolution: [1280, 720]
  output_fps: 30
  
data:
  raw_data_path: 'data/raw'
  processed_data_path: 'data/processed'
  annotations_path: 'data/annotations'
  models_path: 'models'
  
annotation:
  formats: ['yolo', 'coco', 'pascal_voc']
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1