# Driver Behavior Detection Configuration

# Detection Thresholds
thresholds:
  drowsiness:
    ear_threshold: 0.25  # Eye Aspect Ratio threshold
    consecutive_frames: 15  # Number of consecutive frames before alert

  yawning:
    mar_threshold: 0.5  # Mouth Aspect Ratio threshold
    consecutive_frames: 15

  distraction:
    head_pose_threshold: 30  # degrees
    head_pose_frames: 20
    gaze_deviation_threshold: 35  # degrees
    gaze_frames: 25

  phone_usage:
    position_threshold: 0.15  # distance threshold
    consecutive_frames: 10

  smoking:
    position_threshold: 0.1  # distance to mouth
    consecutive_frames: 15

# Alert Settings
alerts:
  cooldown_seconds: 3  # Minimum time between same alerts
  voice_enabled: true
  voice_rate: 150  # Speech rate
  voice_volume: 0.9
  beep_enabled: true

  severity_levels:
    DROWSY: CRITICAL
    PHONE_USAGE: HIGH
    SMOKING_DETECTED: HIGH
    DISTRACTED: MEDIUM
    YAWNING: LOW
    GAZE_DISTRACTED: MEDIUM

# Recording Settings
recording:
  enable_auto_record: false  # Auto record when alert triggered
  output_directory: "logs/recordings"
  video_format: "mp4v"
  fps: 20
  save_snapshots: true

# MediaPipe Settings
mediapipe:
  max_num_faces: 1
  max_num_hands: 2
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  refine_landmarks: true

# Display Settings
display:
  show_statistics: true
  show_fps: true
  show_landmarks: true
  panel_height: 200
  alert_overlay_opacity: 0.3

# Logging
logging:
  enable_event_log: true
  log_file: "logs/events.csv"
  log_level: "INFO"

# Camera Settings
camera:
  default_source: 0  # 0 for default webcam
  resolution:
    width: 640
    height: 480
  fps_limit: 30

# Performance
performance:
  skip_frames: 0  # Process every Nth frame (0 = process all)
  use_gpu: false  # Use GPU acceleration if available